### ISSUE TITLE
Does not work in iTerm2 v3

### ISSUE THREAD

**Issue by Clan-Utility** [pose/node-iterm2-image#2]
The example does not work in iTerm2 v3.
Btw, what is imgLoader?

**Comment by pose** [comment]
Hi @Clan-Utility,

Can you tell how to reproduce the issue? It's working for me. What are you getting when you execute `node example.js`?

Thanks in advance,

**Comment by Clan-Utility** [comment]
It's working. I was just confused by 'imgLoader' in the example. 

In the example, the following 2 lines

```
drawInIterm('./path-to-file.png', function () {
imgLoader('./path-to-file.png', function (err) {
```

should be 

```
drawInIterm('./path-to-file.png', function (err) {
```
