### ISSUE TITLE
SVG Support?

### ISSUE THREAD

**Issue by F1LT3R** [pose/node-iterm2-image#6]
Firstly, thanks for this simple lib. Very useful :)

It works well for me, except for SVG. Here is the output I get.

<img width="1440" alt="screen shot 2018-03-29 at 8 45 45 am" src="https://user-images.githubusercontent.com/1218446/38089504-a29c2cb8-332d-11e8-8f56-76fbcf84f8d5.png">

Here is my source:

```js
const drawInIterm = require('iterm2-image');

drawInIterm('./ansi-to-svg.svg', function (err) {
	console.log(err)
});

```

**Comment by pose** [comment]
Hi @F1LT3R, 

It's not a limitation of this library but it's caused by iterm2 not supporting that format:

https://gitlab.com/gnachman/iterm2/issues/6479

Feel free to re-open this issue when that feature is supported.

Thanks in advance,
